<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        border: 2px solid #444444;
        text-align: center;
    }

    div#more-information
    {
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">eCard Registration</span> Demo Page</h1>

    <h3>This is the main page</h3>

    <div id="more-information">
        <p>
            Helpful Links: <br />
                <a href="/contact/register">Registration page</a> |
            <a href="/contact">List Registered Contacts</a>
        </p>
    </div>
</div>